# Required
dir: lib/feature

format: true
nullable-getter: false

parts:
  - name: settings
    outputDir: /lib/core/localizations/gen
    template-arb-file: settings_ru.arb
    outputLocalizationFile: settings_lcl.dart