name: l10n_decompose_example
description: "Example of l10n_decompose package"
publish_to: 'none'
version: 0.1.0

resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  l10n_decompose:
    path: ../

flutter:
  uses-material-design: true
  generate: true

l10n_decompose:
  enabled: true
  input: "**_en.arb"
  output: l10n/*_localization.dart

  format: true
  nullable-getter: false

  composite:
    enabled: true
    # Optional; By default relative to lib directory.
    outputFile: lib/core/l10n/composite_localizations.dart
    # Optional; By default CompositeLocalizations
    outputClass: CompositeLocalizations

  parts:
    - name: settings
      output: localization/gen/settings_locale.dart
      outputClass: SettingsLocalization