name: package_name

l10n_decompose:
  # Optional;
  enabled: true
  # Optional; By default `"**_en.arb"`
  # Available patterns for template file:
  # - **_en.arb
  # - **_en_US.arb
  # The prefix style can be any, but it is recommended to use the `snake_case` style.
  input: "**_en.arb"

  #Optional; By default `gen/*_localization.dart`
  output: gen/*_localization.dart

  #Optional; By default use pattern *Localizations or static name.
  output-class: "*Localizations"

  #Optional; By default false inherited from flutter gen-l10n
  format: false

  #Optional; By default true inherited from flutter gen-l10n
  nullable-getter: true

  #Optional; By default false
  composite:
    # Required;
    enabled: true
    # Optional; By default relative to lib directory.
    outputFile: lib/general_localizations.dart
    # Optional; By default GeneralLocalizations
    outputClass: GeneralLocalizations

  # Optional; Customize output
  parts:
    # Required;
    - name: core
      # Optional; By default use Global settings
      # Relative - dir/app_locale.dart OR ./dir/app_locale.dart
      # Absolute - /lib/app_locale.dart or lib/app_locale.dart
      output: localization/app_locale.dart
      # Optional; By default use Global settings
      outputClass: AppLocale