# Required
dir: lib/feature

# Optional; Use pattern %_en.arb or static name.
template-arb-file: "%_en.arb"

#Optional; By default l10n
arb-dir: l10n

#Optional; By default localization
output-dir: localization

#Optional; By default use pattern %_localization.dart or static name.
output-localization-file: "%_localization.dart"

#Optional; By default use pattern %Localizations or static name.
output-class: "%Localizations"

#Optional; By default false inherited from flutter gen-l10n
format: false

#Optional; By default true inherited from flutter gen-l10n
nullable-getter: true

# Optional; 
parts:
  # Required;
  - name: home
    # Optional; Use pattern %_en.arb or static name.
    template-arb-file: home_en.arb
    # Optional; By default l10n
    arbDir: l10n
    # Optional; By default localization
    outputDir: localization
    # Optional; By default use pattern %_localization.dart or static name.
    outputLocalizationFile: main_locale.dart
    # Optional; By default use pattern %Localizations or static name.
    outputClass: MainLocale